parameters:
    swm.mail_hook.service.mail_hook.class: Swm\Bundle\MailHookBundle\Service\MailHookService
    swm.mail_hook.provider.api_service.class: Swm\Bundle\MailHookBundle\Provider\ApiServiceProvider
    swm.mail_hook.hydrator.default.class: Swm\Bundle\MailHookBundle\Hydrator\DefaultHydrator
    swm.mail_hook.hydrator.fos_user.class: Swm\Bundle\MailHookBundle\Hydrator\FosUserHydrator

services:
    _default:
        public: true

    swm.mail_hook.service.mail_hook:
        class: "%swm.mail_hook.service.mail_hook.class%"
        shared: false
        arguments:
            - "@request_stack"
            - "@swm.mail_hook.provider.api_service"

    swm.mail_hook.provider.api_service:
        class: "%swm.mail_hook.provider.api_service.class%"

    swm.mail_hook.hydrator.default:
        class: "%swm.mail_hook.hydrator.default.class%"

