parameters:
    swm.mail_hook.service.mail_hook.class: Swm\Bundle\MailHookBundle\Service\MailHookService
    swm.mail_hook.provider.api_service.class: Swm\Bundle\MailHookBundle\Provider\ApiServiceProvider
    swm.mail_hook.hydrator.default.class: Swm\Bundle\MailHookBundle\Hydrator\DefaultHydrator

services:
    swm.mail_hook.service.mail_hook:
        class: %swm.mail_hook.service.mail_hook.class%
        scope: request
        arguments:
            - @request
            - @swm.mail_hook.provider.api_service

    swm.mail_hook.provider.api_service:
        class: %swm.mail_hook.provider.api_service.class%

    swm.mail_hook.hydrator.default:
        class: %swm.mail_hook.hydrator.default.class%

    swm.mail_hook.hydrator.fos_user:
        class: %swm.mail_hook.hydrator.default.class%
        arguments:
            - @fos_user.user_manager